config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  resources :users do
    resources :posts do
      resources :likes, only: [:create]
      resources :comments, only: [:new, :create]
    end
  end

  delete "/posts/:id", to: "posts#destroy", as: :destroy_post
  delete "/posts/:post_id/comments/:id", to: "comments#destroy", as: :destroy_comment

  root to: "users#index"

namespace :api do
  namespace :v1 do
    resources :users do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Comment, author: user
      can :destroy, Post, author: user
    end
  end
end

app/models/application_record.rb
# rubocop:disable all

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, foreign_key: 'post_id'
  belongs_to :author, class_name: 'User'
  after_save :update_comments_counter
  after_destroy :reduce_comment_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  def reduce_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  after_save :update_posts_counter
  after_destroy :reduce_posts_counter
  after_initialize :set_defaults

  def update_posts_counter
    author.increment!(:postsCounter)
  end

  def reduce_posts_counter
    author.decrement!(:postsCounter)
  end

  def set_defaults
    self.likes_counter ||= 0
    self.comments_counter ||= 0
  end

  def return_five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
# app/models/user.rb

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  after_initialize :update_posts_counter

  def update_posts_counter
    update(postsCounter: posts.count)
  end

  def return_three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_spec.rb
require 'swagger_helper'

RSpec.describe 'Post Comments API', type: :request, swagger_doc: 'v1/swagger.json' do
  path '/api/v1/users/{user_id}/posts/{post_id}/comments' do
    parameter name: 'user_id', in: :path, type: :integer, required: true
    parameter name: 'post_id', in: :path, type: :integer, required: true

    get 'Retrieves comments of a post' do
      tags 'Post Comments'
      produces 'application/json'

      response '200', 'comments found' do
        schema type: :array,
          items: { '$ref' => '#/components/schemas/Comment' }
        let(:user) { create(:user) }
        let(:post) { create(:post, user: user) }
        let(:user_id) { user.id }
        let(:post_id) { post.id }
        run_test!
      end
    end
  end
end

app/controllers/api/v1/create_comment_spec.rb
require 'swagger_helper'

RSpec.describe 'Create Comment API', type: :request, swagger_doc: 'v1/swagger.json' do
  path '/api/v1/posts/{post_id}/comments' do
    parameter name: 'post_id', in: :path, type: :integer, required: true

    post 'Creates a comment for a post' do
      tags 'Create Comment'
      consumes 'application/json'
      parameter name: :comment, in: :body, schema: {
        type: :object,
        properties: {
          text: { type: :string }
        },
        required: ['text']
      }

      response '201', 'comment created' do
        let(:user) { create(:user) }
        let(:post) { create(:post) }
        let(:user_id) { user.id }
        let(:post_id) { post.id }
        let(:comment) { { text: 'A new comment' } }
        run_test!
      end
    end
  end
end

app/controllers/api/v1/users_spec.rb
require 'swagger_helper'

RSpec.describe 'User Posts API', type: :request, swagger_doc: 'v1/swagger.json' do
  path '/api/v1/users/{user_id}/posts' do
    parameter name: 'user_id', in: :path, type: :integer, required: true

    get 'Retrieves posts of a user' do
      tags 'User Posts'
      produces 'application/json'

      response '200', 'posts found' do
        schema type: :array,
          items: { '$ref' => '#/components/schemas/Post' }
        let(:user) { create(:user) }
        let(:user_id) { user.id }
        run_test!
      end
    end
  end
end

app/controllers/application_controller.rb
# rubocop:disable all


class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the required parameters for user sign-up
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo, :bio, :email, :password, :password_confirmation])
  end
end

app/controllers/comments_controller.rb
# app/controllers/api/v1/comments_controller.rb

module Api
  module V1
    class CommentsController < ApplicationController
      before_action :set_post

      def create
        comment = @post.comments.build(comment_params)
        comment.user = current_user

        if comment.save
          render json: comment, status: :created
        else
          render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def index
        comments = @post.comments
        render json: comments
      end

      private

      def set_post
        @post = Post.find(params[:post_id])
      end

      def comment_params
        params.require(:comment).permit(:text)
      end
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @like = Like.new(author: @user, post: @post)

    if @like.save
      redirect_to user_post_path(user_id: @post.author, id: @post), notice: 'Post liked successfully.'
    else
      redirect_to user_post_path(user_id: @post.author, id: @post), alert: 'Failed to like the post.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource # except: %i[index show]
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(user_id: current_user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.author
    @post.destroy
    redirect_to user_path(@user), notice: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.includes(:posts)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:comments)
  end
end

app/helpers/application_helper.rb
# rubocop:disable all

module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<!-- app/views/comments/new.html.erb -->

<h1>Add a Comment</h1>

<%= form_with model: @comment, url: post_comments_path(@post) do |form| %>
  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit "Add Comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GemBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Posts</title>
</head>
<body>
  <h1>Posts for <%= @user.name %></h1>

  <% @posts.each do |post| %>
    <div class="post">
      <%= link_to 'View Comments', user_post_path(user_id: @user, id: post) %>
      <h3><%= post.title %></h3>
      <p><%= post.text %></p>

      <p class="cmt-likes"><strong>Comments:</strong> <%= post.comments.count %> &nbsp;&nbsp; <strong>Likes:</strong> <%= post.likes.count %></p>


      <% if can? :destroy, post %>
  <%= form_for [@user, post], url: post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do |f| %>
    <%= f.submit "Delete Post" %>
  <% end %>
<% end %>


      <% post.return_five_most_recent_comments.each do |comment| %>
        <p><strong><%= comment.author.name %>:</strong> <%= comment.text %></p>
      <% end %>
    </div>
  <% end %>

  <button>Pagination</button>
</body>
</html>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->

<h1>Create a New Post</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :text %>
  <%= form.text_area :text %>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post Details</title>
</head>
<body>
  <div class="post-card">
    <p class="comt-likes"><strong>Comments:</strong> <%= @post.comments.count %> &nbsp;&nbsp; <strong>Likes:</strong> <%= @post.likes.count %></p>
    <h5><%= @post.title %> by <%= @post.author.name %></h5>
    <p><%= @post.text %></p>
  </div>

  <div class="post-cmts">
    <h2>comments:</h2>
    <% @post.comments.each do |comment| %>
      <p><strong><%= comment.author.name %>:</strong> <%= comment.text %></p>
<% if current_user && current_user == comment.author %>  
  <%= button_to 'Delete', post_comment_path(current_user, @post), method: :delete, class: 'delete-btn' %>  
    <% end %>
    <% end %>
  </div>



  <%= link_to 'Add Comment', new_post_comment_path(@post) %>




  <%= form_with url: post_likes_path(@post.author, @post) do |form| %>
    <%= form.submit 'Like', class: 'like_btn' %>
  <% end %>
</body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User List</title>
</head>
<body>
  <h1>User List</h1>

  <% @users.each do |user| %>
    <div class="Users-card">
      <img class="User-img" src="<%= user.photo %>" alt="User Image">
      <div class="user-inn">
        <h2><%= user.name %></h2>
        <p>Number Of Posts: <%= user.postsCounter %></p>
        <% if user_signed_in? && current_user == user %>
          <%= link_to 'View My Profile', user_path(user) %>
        <% else %>
          <%= link_to 'View Profile', user_path(user) %>
        <% end %>
      </div>
    </div>
  <% end %>
</body>
</html>

app/views/user/show.html.erb
<!-- app/views/user/show.html.erb -->

<div class="Users-card">
  <img class="User-img" src="<%= @user.photo %>" alt="User Image">
  <div class="user-inn">
    <h2><%= @user.name %></h2>
    <p>Number Of Posts: <%= @user.postsCounter %></p>
  </div>
</div>
<div class="user-bio">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>

<% @user.return_three_most_recent_posts.each do |post| %>
  <div class="post">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <p class="cmt-likes"><strong>Comments:</strong> <%= post.comments.count %> &nbsp;&nbsp; <strong>Likes:</strong> <%= post.likes.count %></p>
    <%= link_to 'View Comments', user_post_path(user_id: @user, id: post) %>
  </div>
<% end %>

<% if user_signed_in? && current_user == @user %>
  <%= link_to 'Add Post', new_post_path %>
<% end %>

<%= link_to 'See All Posts', user_posts_path(user_id: @user) %>